data: 'pubmed'

epochs: 200
learning_rate: 0.001

device: 'cuda:0'
seed: 2025

partition: 'metis' # metis, louvain, balanced_lpa, infomap
sample_method: 'remove_isolated' # remove_isolated, extract_lcc
recon_method: 'synth' # synth, cellsbm, random
hidden_dim: 64
latent_dim: 64
label_size: 32
link_hidden_dim: 128

resume: false
epochs_save_ckpt: 50 # Save a checkpoint every N epochs